# Generated by Django 3.1.2 on 2020-10-31 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercewebapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('S', 'Shipping'), ('B', 'Billing')], default='S', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
