# Generated by Django 3.1.2 on 2020-11-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercewebapp', '0004_auto_20201101_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_requested_date',
        ),
    ]
