# Generated by Django 3.1.2 on 2020-11-01 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercewebapp', '0005_remove_order_refund_requested_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
            ],
        ),
    ]
