# Generated by Django 3.1.2 on 2020-11-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercewebapp', '0007_auto_20201101_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
